apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
  namespace: devops
  labels:
    app: nginx-dev
spec:
  
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dev
  template:
    
    metadata:
      labels:
        app: nginx-dev
    spec:
      serviceAccountName: bilbo
      containers:
      - name: nginx
        image: nginx:1.21.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
