apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: devops

  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30090
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
